// MarketplaceSite/js/ListingDetail.jsx
// ============================================================
// ListingDetail — full detail page: gallery, info, contact form
// ============================================================

function ListingDetail({ listing, navigate, favorites, onToggleFavorite }) {
  const [activeThumb, setActiveThumb] = React.useState(0);
  const [form, setForm] = React.useState({ name: "", email: "", phone: "", message: "" });
  const [errors, setErrors] = React.useState({});
  const [sent, setSent] = React.useState(false);

  const isFav = favorites.has(listing.id);
  const cfg = CATEGORY_STYLE[listing.category] || CATEGORY_STYLE["Altele"];
  const THUMB_COUNT = 4;

  const statusBadge = {
    active: null,
    sold:   <span className="bg-red-100 text-red-700 text-xs font-bold px-2.5 py-0.5 rounded-full uppercase tracking-wide">Vândut</span>,
    paused: <span className="bg-yellow-100 text-yellow-700 text-xs font-bold px-2.5 py-0.5 rounded-full uppercase tracking-wide">Pauză</span>,
  }[listing.status];

  const validate = () => {
    const e = {};
    if (!form.name.trim())   e.name    = "Câmp obligatoriu";
    if (!form.email.includes("@")) e.email = "Email invalid";
    if (!form.message.trim()) e.message = "Câmp obligatoriu";
    return e;
  };

  const handleSend = ev => {
    ev.preventDefault();
    const e = validate();
    if (Object.keys(e).length) { setErrors(e); return; }
    setSent(true);
  };

  const field = (key, value) => {
    setForm({ ...form, [key]: value });
    setErrors({ ...errors, [key]: "" });
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-6">

      {/* Back */}
      <button
        onClick={() => navigate("home")}
        className="flex items-center gap-2 text-sm text-gray-500 hover:text-gray-900 mb-6 group transition-colors"
      >
        <IconsSVG name="arrow-left" size={15} className="group-hover:-translate-x-0.5 transition-transform" />
        Înapoi la anunțuri
      </button>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

        {/* ── Left column: gallery + description ── */}
        <div className="lg:col-span-2 space-y-5">

          {/* Gallery */}
          <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
            {/* Main image */}
            <div className={`${cfg.area} aspect-[16/9] flex items-center justify-center border-b border-gray-100`}>
              <div className="flex flex-col items-center gap-3 opacity-20 select-none">
                <IconsSVG name="image" size={64} className="text-gray-500" />
                <span className="text-sm font-mono text-gray-500">fotografie {activeThumb + 1} / {THUMB_COUNT}</span>
              </div>
            </div>

            {/* Thumbnails */}
            <div className="p-3 flex gap-2">
              {Array.from({ length: THUMB_COUNT }).map((_, i) => (
                <button
                  key={i}
                  onClick={() => setActiveThumb(i)}
                  className={`w-16 h-16 shrink-0 rounded-lg border-2 transition-all ${cfg.area} flex items-center justify-center ${activeThumb === i ? "border-green-500 opacity-100" : "border-transparent opacity-50 hover:opacity-80"}`}
                >
                  <IconsSVG name="image" size={18} className="text-gray-400" />
                </button>
              ))}
            </div>
          </div>

          {/* Description */}
          <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6">
            <h2 className="font-semibold text-gray-900 mb-4">Descriere</h2>
            <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-line">{listing.description}</p>

            {/* Meta grid */}
            <div className="mt-6 pt-5 border-t border-gray-100 grid grid-cols-2 sm:grid-cols-4 gap-4 text-sm">
              {[
                { label: "Categorie", val: listing.category },
                { label: "Oraș",      val: listing.city },
                { label: "Postare",   val: listing.date },
                { label: "Vizualizări", val: listing.views },
              ].map(item => (
                <div key={item.label}>
                  <p className="text-xs text-gray-400 mb-0.5">{item.label}</p>
                  <p className="font-semibold text-gray-900">{item.val}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ── Right column: price + seller + contact ── */}
        <div className="space-y-4">

          {/* Price card */}
          <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-5">
            <div className="flex items-start justify-between gap-2 mb-1">
              <h1 className="text-sm font-semibold text-gray-900 leading-snug flex-1">{listing.title}</h1>
              {statusBadge}
            </div>

            <p className="text-3xl font-bold text-green-600 mt-2 mb-1">
              {listing.price.toLocaleString("ro-RO")}
              <span className="text-lg font-semibold text-green-500 ml-1">RON</span>
            </p>

            <div className="flex items-center gap-1.5 text-sm text-gray-500 mb-1">
              <IconsSVG name="map-pin" size={13} />
              {listing.city}
            </div>

            <span className={`inline-block text-xs font-medium px-2 py-0.5 rounded-md mt-1 ${cfg.badge}`}>
              {listing.category}
            </span>

            <button
              onClick={() => onToggleFavorite(listing.id)}
              className={`w-full flex items-center justify-center gap-2 mt-4 py-2.5 rounded-lg border text-sm font-semibold transition-colors ${
                isFav
                  ? "border-red-200 text-red-500 bg-red-50 hover:bg-red-100"
                  : "border-gray-200 text-gray-700 hover:bg-gray-50"
              }`}
            >
              <IconsSVG name="heart" size={15} fill={isFav ? "currentColor" : "none"} className={isFav ? "text-red-500" : ""} />
              {isFav ? "Eliminat din favorite" : "Adaugă la favorite"}
            </button>
          </div>

          {/* Seller card */}
          <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-5">
            <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">Vânzător</p>
            <div className="flex items-center gap-3 mb-3">
              <div className="w-11 h-11 bg-green-100 text-green-700 rounded-full flex items-center justify-center font-bold text-lg shrink-0">
                {listing.seller.name[0]}
              </div>
              <div>
                <p className="font-semibold text-gray-900 text-sm">{listing.seller.name}</p>
                <div className="flex items-center gap-1 text-xs text-gray-500 mt-0.5">
                  <span className="text-yellow-400 text-sm">★</span>
                  <span className="font-semibold text-gray-700">{listing.seller.rating}</span>
                  <span>· {listing.seller.totalListings} anunțuri</span>
                </div>
              </div>
            </div>
            <p className="text-xs text-gray-400">Membru din {listing.seller.memberSince}</p>
          </div>

          {/* Contact form */}
          <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-5">
            <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">Contactează vânzătorul</p>

            {sent ? (
              <div className="text-center py-6">
                <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-3">
                  <IconsSVG name="check" size={22} className="text-green-600" />
                </div>
                <p className="font-semibold text-gray-900 text-sm mb-1">Mesaj trimis!</p>
                <p className="text-xs text-gray-500 mb-4">Vânzătorul va răspunde în curând.</p>
                <button onClick={() => setSent(false)} className="text-xs text-green-600 font-semibold hover:text-green-700">
                  Trimite alt mesaj
                </button>
              </div>
            ) : (
              <form onSubmit={handleSend} className="space-y-3">
                {[
                  { key: "name",    type: "text",  ph: "Numele tău",   icon: "user" },
                  { key: "email",   type: "email", ph: "Email",         icon: "at-sign" },
                  { key: "phone",   type: "tel",   ph: "Telefon (opț.)", icon: "phone" },
                ].map(({ key, type, ph, icon }) => (
                  <div key={key}>
                    <div className="relative">
                      <div className="absolute inset-y-0 left-3 flex items-center pointer-events-none">
                        <IconsSVG name={icon} size={14} className="text-gray-400" />
                      </div>
                      <input
                        type={type}
                        placeholder={ph}
                        value={form[key]}
                        onChange={e => field(key, e.target.value)}
                        className={`w-full pl-9 pr-3 py-2.5 text-sm border rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 transition-colors ${errors[key] ? "border-red-300 bg-red-50" : "border-gray-200"}`}
                      />
                    </div>
                    {errors[key] && <p className="text-xs text-red-500 mt-1">{errors[key]}</p>}
                  </div>
                ))}

                <div>
                  <textarea
                    placeholder="Mesajul tău..."
                    rows={4}
                    value={form.message}
                    onChange={e => field("message", e.target.value)}
                    className={`w-full px-3 py-2.5 text-sm border rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 resize-none transition-colors ${errors.message ? "border-red-300 bg-red-50" : "border-gray-200"}`}
                  />
                  {errors.message && <p className="text-xs text-red-500 mt-0.5">{errors.message}</p>}
                </div>

                <button
                  type="submit"
                  className="w-full bg-green-600 text-white font-semibold py-2.5 rounded-lg hover:bg-green-700 transition-colors text-sm"
                >
                  Trimite mesajul
                </button>
              </form>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

window.ListingDetail = ListingDetail;

// client/src/app/features/listings/listing-detail/listing-detail.component.ts
import { Component, OnInit, inject, Input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { ListingService } from '../../../_services/listing.service';
import { FavoritesService } from '../../../_services/favorites.service';
import { ContactService } from '../../../_services/contact.service';
import { AccountService } from '../../../_services/account.service';
import { Listing } from '../../../_models/listing.model';
import { SvgIconComponent } from '../../../shared/svg-icon.component';

@Component({
  selector: 'app-listing-detail',
  standalone: true,
  imports: [CommonModule, RouterLink, ReactiveFormsModule, SvgIconComponent],
  templateUrl: './listing-detail.component.html'
})
export class ListingDetailComponent implements OnInit {
  @Input() id!: string;  // Angular 17: route param injected via withComponentInputBinding()

  private listingService = inject(ListingService);
  private favoritesService = inject(FavoritesService);
  private contactService = inject(ContactService);
  accountService = inject(AccountService);
  private fb = inject(FormBuilder);

  listing: Listing | null = null;
  loading = true;
  selectedImageIndex = 0;

  // Contact form
  contactForm: FormGroup = this.fb.group({
    senderName: ['', Validators.required],
    senderEmail: ['', [Validators.required, Validators.email]],
    senderPhone: [''],
    message: ['', [Validators.required, Validators.minLength(10), Validators.maxLength(1000)]]
  });
  contactLoading = false;
  contactSuccess = false;
  contactError = '';

  isFavorited = false;
  favoriteLoading = false;

  ngOnInit(): void {
    this.listingService.getListing(this.id).subscribe({
      next: listing => {
        this.listing = listing;
        this.isFavorited = listing.isFavoritedByCurrentUser;
        this.loading = false;

        // Pre-fill contact form with logged-in user data
        const user = this.accountService.currentUser();
        if (user) {
          this.contactForm.patchValue({
            senderName: user.username,
            senderEmail: user.email
          });
        }
      },
      error: () => this.loading = false
    });
  }

  toggleFavorite(): void {
    if (!this.accountService.isLoggedIn() || !this.listing) return;
    this.favoriteLoading = true;

    const action$ = this.isFavorited
      ? this.favoritesService.removeFavorite(this.listing.id)
      : this.favoritesService.addFavorite(this.listing.id);

    action$.subscribe({
      next: () => {
        this.isFavorited = !this.isFavorited;
        this.favoriteLoading = false;
      },
      error: () => this.favoriteLoading = false
    });
  }

  sendContactRequest(): void {
    if (this.contactForm.invalid || !this.listing) return;
    this.contactLoading = true;
    this.contactError = '';

    this.contactService.sendContactRequest(this.listing.id, this.contactForm.value).subscribe({
      next: () => {
        this.contactSuccess = true;
        this.contactLoading = false;
        this.contactForm.reset();
      },
      error: err => {
        this.contactError = err.error?.message || 'Eroare la trimiterea mesajului';
        this.contactLoading = false;
      }
    });
  }

  get isOwner(): boolean {
    return this.listing?.seller.id === this.accountService.currentUser()?.id;
  }
}

<div class="max-w-7xl mx-auto px-4 sm:px-6 py-6">

  <!-- Back button -->
  <button onclick="history.back()"
          class="flex items-center gap-2 text-sm text-gray-500 hover:text-gray-900 mb-6 group transition-colors">
    <app-icon name="arrow-left" [size]="15"></app-icon>
    Înapoi la anunțuri
  </button>

  @if (loading) {
    <div class="animate-pulse grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div class="lg:col-span-2 space-y-4">
        <div class="bg-gray-200 aspect-[16/9] rounded-2xl"></div>
        <div class="h-8 bg-gray-200 rounded w-3/4"></div>
      </div>
    </div>
  }

  @if (!loading && listing) {
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">

      <!-- Left: Gallery + Description -->
      <div class="lg:col-span-2 space-y-5">

        <!-- Gallery -->
        <div class="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
          <div class="aspect-[16/9] bg-gray-100 flex items-center justify-center">
            @if (listing.images[selectedImageIndex]?.imageUrl || listing.mainImageUrl) {
              <img [src]="listing.images[selectedImageIndex]?.imageUrl || listing.mainImageUrl"
                   [alt]="listing.title" class="w-full h-full object-contain">
            } @else {
              <div class="flex flex-col items-center gap-3 opacity-20">
                <app-icon name="image" [size]="64"></app-icon>
              </div>
            }
          </div>
          @if (listing.images.length > 1) {
            <div class="p-3 flex gap-2 overflow-x-auto">
              @for (img of listing.images; track img.id; let i = $index) {
                <button (click)="selectedImageIndex = i"
                        class="w-16 h-16 shrink-0 rounded-lg border-2 overflow-hidden transition-all"
                        [class.border-green-500]="i === selectedImageIndex"
                        [class.border-transparent]="i !== selectedImageIndex"
                        [class.opacity-50]="i !== selectedImageIndex">
                  <img [src]="img.imageUrl" class="w-full h-full object-cover">
                </button>
              }
            </div>
          }
        </div>

        <!-- Description -->
        <div class="bg-white rounded-2xl border border-gray-200 shadow-sm p-6">
          <h2 class="font-semibold text-gray-900 mb-4">Descriere</h2>
          <p class="text-sm text-gray-700 leading-relaxed whitespace-pre-line">{{ listing.description }}</p>

          <div class="mt-6 pt-5 border-t border-gray-100 grid grid-cols-2 sm:grid-cols-4 gap-4 text-sm">
            <div>
              <p class="text-xs text-gray-400 mb-0.5">Categorie</p>
              <p class="font-semibold text-gray-900">{{ listing.categoryName }}</p>
            </div>
            <div>
              <p class="text-xs text-gray-400 mb-0.5">Oraș</p>
              <p class="font-semibold text-gray-900">{{ listing.city }}</p>
            </div>
            <div>
              <p class="text-xs text-gray-400 mb-0.5">Postare</p>
              <p class="font-semibold text-gray-900">{{ listing.createdAt | date:'dd MMM yyyy' }}</p>
            </div>
            <div>
              <p class="text-xs text-gray-400 mb-0.5">Status</p>
              <span class="text-xs font-semibold px-2 py-0.5 rounded-full"
                    [class.bg-green-100]="listing.status==='Active'" [class.text-green-700]="listing.status==='Active'"
                    [class.bg-red-100]="listing.status==='Sold'" [class.text-red-600]="listing.status==='Sold'"
                    [class.bg-yellow-100]="listing.status==='Paused'" [class.text-yellow-700]="listing.status==='Paused'">
                {{ listing.status === 'Active' ? 'Activ' : listing.status === 'Sold' ? 'Vândut' : 'Pauză' }}
              </span>
            </div>
          </div>

          @if (isOwner) {
            <div class="mt-5 pt-4 border-t">
              <a [routerLink]="['/listings', listing.id, 'edit']"
                 class="flex items-center gap-1.5 text-sm font-medium text-gray-700 border border-gray-300 px-3 py-2 rounded-lg hover:bg-gray-50 transition-colors w-fit">
                <app-icon name="edit" [size]="14"></app-icon>
                Editează anunțul
              </a>
            </div>
          }
        </div>
      </div>

      <!-- Right: Price + Seller + Contact -->
      <div class="space-y-4">

        <!-- Price card -->
        <div class="bg-white rounded-2xl border border-gray-200 shadow-sm p-5">
          <h1 class="text-sm font-semibold text-gray-900 leading-snug mb-2">{{ listing.title }}</h1>

          <p class="text-3xl font-bold text-green-600 mt-2 mb-1">
            {{ listing.price | number:'1.0-0' }}
            <span class="text-lg font-semibold text-green-500 ml-1">RON</span>
          </p>
          @if (listing.isNegotiable) {
            <span class="text-xs text-gray-500 bg-gray-100 px-2 py-0.5 rounded-full">negociabil</span>
          }

          <div class="flex items-center gap-1.5 text-sm text-gray-500 mt-2">
            <app-icon name="map-pin" [size]="13"></app-icon>
            {{ listing.city }}
          </div>

          @if (accountService.isLoggedIn() && !isOwner) {
            <button (click)="toggleFavorite()" [disabled]="favoriteLoading"
                    class="w-full flex items-center justify-center gap-2 mt-4 py-2.5 rounded-lg border text-sm font-semibold transition-colors"
                    [class.border-red-200]="isFavorited" [class.text-red-500]="isFavorited" [class.bg-red-50]="isFavorited"
                    [class.border-gray-200]="!isFavorited" [class.text-gray-700]="!isFavorited" [class.hover:bg-gray-50]="!isFavorited">
              <app-icon [name]="isFavorited ? 'heart-filled' : 'heart'" [size]="15"
                        [class.text-red-500]="isFavorited"></app-icon>
              {{ isFavorited ? 'Eliminat din favorite' : 'Adaugă la favorite' }}
            </button>
          }
        </div>

        <!-- Seller card -->
        <div class="bg-white rounded-2xl border border-gray-200 shadow-sm p-5">
          <p class="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">Vânzător</p>
          <div class="flex items-center gap-3 mb-3">
            @if (listing.seller.profilePicture) {
              <img [src]="listing.seller.profilePicture" class="w-11 h-11 rounded-full object-cover">
            } @else {
              <div class="w-11 h-11 bg-green-100 text-green-700 rounded-full flex items-center justify-center font-bold text-lg shrink-0">
                {{ listing.seller.username.charAt(0).toUpperCase() }}
              </div>
            }
            <div>
              <p class="font-semibold text-gray-900 text-sm">{{ listing.seller.username }}</p>
              @if (listing.seller.city) {
                <p class="text-xs text-gray-500 mt-0.5 flex items-center gap-1">
                  <app-icon name="map-pin" [size]="10"></app-icon>
                  {{ listing.seller.city }}
                </p>
              }
            </div>
          </div>
          @if (listing.seller.phoneNumber) {
            <a [href]="'tel:' + listing.seller.phoneNumber"
               class="flex items-center gap-2 text-sm text-green-600 font-medium mt-2 pt-2 border-t border-gray-100">
              <app-icon name="phone" [size]="14"></app-icon>
              {{ listing.seller.phoneNumber }}
            </a>
          }
        </div>

        <!-- Contact form -->
        @if (!isOwner && listing.status === 'Active') {
          <div class="bg-white rounded-2xl border border-gray-200 shadow-sm p-5">
            <p class="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">Contactează vânzătorul</p>

            @if (contactSuccess) {
              <div class="text-center py-6">
                <div class="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-3 text-green-600">
                  <app-icon name="check" [size]="22"></app-icon>
                </div>
                <p class="font-semibold text-gray-900 text-sm mb-1">Mesaj trimis!</p>
                <p class="text-xs text-gray-500">Vânzătorul va răspunde în curând.</p>
              </div>
            } @else {
              @if (contactError) {
                <div class="bg-red-50 border border-red-200 text-red-700 rounded-xl p-3 text-sm mb-3">
                  {{ contactError }}
                </div>
              }
              <form [formGroup]="contactForm" (ngSubmit)="sendContactRequest()" class="space-y-3">
                <div class="relative">
                  <div class="absolute inset-y-0 left-3 flex items-center pointer-events-none text-gray-400">
                    <app-icon name="user" [size]="14"></app-icon>
                  </div>
                  <input formControlName="senderName" type="text" placeholder="Numele tău *"
                         class="w-full pl-9 pr-3 py-2.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 transition-colors">
                </div>
                <div class="relative">
                  <div class="absolute inset-y-0 left-3 flex items-center pointer-events-none text-gray-400">
                    <app-icon name="at-sign" [size]="14"></app-icon>
                  </div>
                  <input formControlName="senderEmail" type="email" placeholder="Email *"
                         class="w-full pl-9 pr-3 py-2.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 transition-colors">
                </div>
                <div class="relative">
                  <div class="absolute inset-y-0 left-3 flex items-center pointer-events-none text-gray-400">
                    <app-icon name="phone" [size]="14"></app-icon>
                  </div>
                  <input formControlName="senderPhone" type="tel" placeholder="Telefon (opț.)"
                         class="w-full pl-9 pr-3 py-2.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 transition-colors">
                </div>
                <div>
                  <textarea formControlName="message" rows="4" placeholder="Mesajul tău..."
                            class="w-full px-3 py-2.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 resize-none transition-colors"></textarea>
                  <p class="text-xs text-gray-400 mt-0.5">{{ contactForm.get('message')?.value?.length || 0 }}/1000</p>
                </div>
                <button type="submit" [disabled]="contactForm.invalid || contactLoading"
                        class="w-full bg-green-600 text-white font-semibold py-2.5 rounded-lg hover:bg-green-700 transition-colors text-sm disabled:opacity-60">
                  @if (contactLoading) { Se trimite... } @else { Trimite mesajul }
                </button>
              </form>
            }
          </div>
        }
      </div>
    </div>
  }
</div>
