// client/src/app/core/navbar/navbar.component.ts
import { Component, inject, HostListener } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AccountService } from '../../_services/account.service';
import { SvgIconComponent } from '../../shared/svg-icon.component';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, SvgIconComponent],
  templateUrl: './navbar.component.html'
})
export class NavbarComponent {
  accountService = inject(AccountService);
  menuOpen = false;
  profileOpen = false;

  @HostListener('document:click', ['$event'])
  onDocumentClick(e: Event) {
    const target = e.target as HTMLElement;
    if (!target.closest('.relative')) {
      this.profileOpen = false;
    }
  }

  logout(): void {
    this.accountService.logout();
    this.menuOpen = false;
    this.profileOpen = false;
  }
}

<nav class="bg-white border-b border-gray-200 sticky top-0 z-50">
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="flex items-center justify-between h-16 gap-4">

      <!-- Logo -->
      <a routerLink="/" (click)="menuOpen=false; profileOpen=false"
         class="flex items-center gap-2.5 shrink-0">
        <div class="w-8 h-8 bg-green-600 rounded-lg flex items-center justify-center text-white">
          <app-icon name="home" [size]="15" [strokeWidth]="2.5"></app-icon>
        </div>
        <span class="font-bold text-lg text-gray-900 tracking-tight">Marketplace</span>
      </a>

      <!-- Desktop right side -->
      <div class="hidden md:flex items-center gap-1">
        <a routerLink="/" routerLinkActive="text-green-600 bg-green-50" [routerLinkActiveOptions]="{exact:true}"
           class="px-3 py-2 text-sm font-medium rounded-lg text-gray-600 hover:text-gray-900 hover:bg-gray-100 transition-colors">
          Anunțuri
        </a>

        @if (accountService.isLoggedIn()) {
          <a routerLink="/favorites"
             routerLinkActive="text-green-600 bg-green-50"
             class="px-3 py-2 text-sm font-medium rounded-lg text-gray-600 hover:text-gray-900 hover:bg-gray-100 transition-colors">
            Favorite
          </a>

          @if (accountService.isAdmin()) {
            <a routerLink="/admin"
               routerLinkActive="text-green-600 bg-green-50"
               class="px-3 py-2 text-sm font-medium rounded-lg text-gray-600 hover:text-gray-900 hover:bg-gray-100 transition-colors">
              Admin
            </a>
          }

          <!-- Add listing CTA -->
          <a routerLink="/listings/create"
             class="flex items-center gap-1.5 bg-green-600 text-white text-sm font-semibold px-4 py-2 rounded-lg hover:bg-green-700 transition-colors ml-1">
            <app-icon name="plus" [size]="14"></app-icon>
            Adaugă
          </a>

          <!-- User dropdown -->
          <div class="relative ml-1">
            <button (click)="profileOpen = !profileOpen; menuOpen=false"
                    class="flex items-center gap-2 px-2 py-1.5 rounded-lg hover:bg-gray-100 transition-colors">
              <div class="w-8 h-8 bg-green-100 text-green-700 rounded-full flex items-center justify-center font-bold text-sm">
                {{ accountService.currentUser()?.username?.charAt(0)?.toUpperCase() }}
              </div>
              <span class="text-sm font-medium text-gray-700">{{ accountService.currentUser()?.username }}</span>
              <app-icon name="chevron-down" [size]="13" class="text-gray-400"></app-icon>
            </button>

            @if (profileOpen) {
              <div class="absolute right-0 top-full mt-1 w-52 bg-white rounded-xl shadow-lg border border-gray-200 py-1 z-50">
                <div class="px-3 py-2.5 border-b border-gray-100">
                  <p class="text-sm font-semibold text-gray-900">{{ accountService.currentUser()?.username }}</p>
                  <p class="text-xs text-gray-500 mt-0.5">{{ accountService.currentUser()?.email }}</p>
                </div>
                <a routerLink="/profile" (click)="profileOpen=false"
                   class="flex items-center gap-2.5 px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors">
                  <app-icon name="user" [size]="14" class="text-gray-400"></app-icon>
                  Profilul meu
                </a>
                <a routerLink="/favorites" (click)="profileOpen=false"
                   class="flex items-center gap-2.5 px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors">
                  <app-icon name="heart" [size]="14" class="text-gray-400"></app-icon>
                  Favorite
                </a>
                <a routerLink="/listings/create" (click)="profileOpen=false"
                   class="flex items-center gap-2.5 px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors">
                  <app-icon name="plus" [size]="14" class="text-gray-400"></app-icon>
                  Adaugă anunț
                </a>
                @if (accountService.isAdmin()) {
                  <a routerLink="/admin" (click)="profileOpen=false"
                     class="flex items-center gap-2.5 px-3 py-2 text-sm text-purple-600 hover:bg-purple-50 transition-colors">
                    <app-icon name="shield" [size]="14" class="text-purple-400"></app-icon>
                    Admin Panel
                  </a>
                }
                <div class="border-t border-gray-100 mt-1 pt-1">
                  <button (click)="logout(); profileOpen=false"
                          class="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-red-500 hover:bg-red-50 transition-colors">
                    <app-icon name="log-out" [size]="14" class="text-red-400"></app-icon>
                    Deconectare
                  </button>
                </div>
              </div>
            }
          </div>

        } @else {
          <a routerLink="/login"
             class="px-4 py-2 text-sm font-medium text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors ml-1">
            Autentificare
          </a>
          <a routerLink="/register"
             class="px-4 py-2 text-sm font-semibold text-white bg-green-600 rounded-lg hover:bg-green-700 transition-colors">
            Înregistrare
          </a>
        }
      </div>

      <!-- Mobile hamburger -->
      <button (click)="menuOpen = !menuOpen; profileOpen=false"
              class="md:hidden p-2 rounded-lg text-gray-600 hover:bg-gray-100 transition-colors">
        @if (menuOpen) {
          <app-icon name="x" [size]="20"></app-icon>
        } @else {
          <app-icon name="menu" [size]="20"></app-icon>
        }
      </button>
    </div>

    <!-- Mobile menu -->
    @if (menuOpen) {
      <div class="md:hidden border-t border-gray-100 py-3 space-y-1">
        <a routerLink="/" (click)="menuOpen=false"
           class="block w-full text-left px-3 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 rounded-lg">
          Anunțuri
        </a>

        @if (accountService.isLoggedIn()) {
          <a routerLink="/favorites" (click)="menuOpen=false"
             class="block w-full text-left px-3 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 rounded-lg">
            Favorite
          </a>
          <a routerLink="/profile" (click)="menuOpen=false"
             class="block w-full text-left px-3 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 rounded-lg">
            Profilul meu
          </a>
          @if (accountService.isAdmin()) {
            <a routerLink="/admin" (click)="menuOpen=false"
               class="block w-full text-left px-3 py-2.5 text-sm font-medium text-purple-600 hover:bg-purple-50 rounded-lg">
              Admin Panel
            </a>
          }
          <a routerLink="/listings/create" (click)="menuOpen=false"
             class="w-full flex items-center justify-center gap-1.5 bg-green-600 text-white text-sm font-semibold rounded-lg px-3 py-2.5 mt-1">
            <app-icon name="plus" [size]="14"></app-icon>
            Adaugă anunț
          </a>
          <button (click)="logout(); menuOpen=false"
                  class="block w-full text-left px-3 py-2.5 text-sm font-medium text-red-500 hover:bg-red-50 rounded-lg">
            Deconectare
          </button>
        } @else {
          <div class="flex gap-2 pt-1">
            <a routerLink="/login" (click)="menuOpen=false"
               class="flex-1 text-center py-2.5 text-sm font-medium text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50">
              Autentificare
            </a>
            <a routerLink="/register" (click)="menuOpen=false"
               class="flex-1 text-center py-2.5 text-sm font-semibold text-white bg-green-600 rounded-lg hover:bg-green-700">
              Înregistrare
            </a>
          </div>
        }
      </div>
    }
  </div>
</nav>

// MarketplaceSite/js/Navbar.jsx
// ============================================================
// Navbar — sticky top navigation
// ============================================================

const { useState: useNavState } = React;

function Navbar({ currentPage, navigate, currentUser, onLogout }) {
  const [mobileOpen, setMobileOpen] = React.useState(false);
  const [profileOpen, setProfileOpen] = React.useState(false);

  const navLinks = [
    { label: "Anunțuri", page: "home" },
    ...(currentUser ? [{ label: "Favorite", page: "favorites" }] : []),
    ...(currentUser && currentUser.role === "admin" ? [{ label: "Admin", page: "admin" }] : []),
  ];

  const closeAll = () => { setMobileOpen(false); setProfileOpen(false); };

  return (
    <nav className="bg-white border-b border-gray-200 sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6">
        <div className="flex items-center justify-between h-16 gap-4">

          {/* ── Logo ── */}
          <button
            onClick={() => { navigate("home"); closeAll(); }}
            className="flex items-center gap-2.5 shrink-0"
          >
            <div className="w-8 h-8 bg-green-600 rounded-lg flex items-center justify-center">
              <IconsSVG name="home" size={15} className="text-white" strokeWidth={2.5} />
            </div>
            <span className="font-bold text-lg text-gray-900 tracking-tight">Marketplace</span>
          </button>

          {/* ── Search bar (desktop) ── */}
          <div className="hidden md:flex flex-1 max-w-sm">
            <div className="relative w-full">
              <div className="absolute inset-y-0 left-3 flex items-center pointer-events-none">
                <IconsSVG name="search" size={15} className="text-gray-400" />
              </div>
              <input
                type="text"
                placeholder="Caută anunțuri..."
                onKeyDown={(e) => e.key === "Enter" && navigate("home")}
                className="w-full pl-9 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-colors"
              />
            </div>
          </div>

          {/* ── Desktop right side ── */}
          <div className="hidden md:flex items-center gap-1">
            {navLinks.map(link => (
              <button
                key={link.page}
                onClick={() => navigate(link.page)}
                className={`px-3 py-2 text-sm font-medium rounded-lg transition-colors ${
                  currentPage === link.page
                    ? "text-green-600 bg-green-50"
                    : "text-gray-600 hover:text-gray-900 hover:bg-gray-100"
                }`}
              >
                {link.label}
              </button>
            ))}

            {currentUser ? (
              <div className="flex items-center gap-2 ml-1">
                {/* Add listing CTA */}
                <button
                  onClick={() => navigate("create")}
                  className="flex items-center gap-1.5 bg-green-600 text-white text-sm font-semibold px-4 py-2 rounded-lg hover:bg-green-700 transition-colors"
                >
                  <IconsSVG name="plus" size={14} />
                  Adaugă
                </button>

                {/* User dropdown */}
                <div className="relative">
                  <button
                    onClick={() => setProfileOpen(!profileOpen)}
                    className="flex items-center gap-2 px-2 py-1.5 rounded-lg hover:bg-gray-100 transition-colors"
                  >
                    <div className="w-8 h-8 bg-green-100 text-green-700 rounded-full flex items-center justify-center font-bold text-sm">
                      {currentUser.name[0]}
                    </div>
                    <span className="text-sm font-medium text-gray-700">{currentUser.name.split(" ")[0]}</span>
                    <IconsSVG name="chevron-down" size={13} className="text-gray-400" />
                  </button>

                  {profileOpen && (
                    <div className="absolute right-0 top-full mt-1 w-52 bg-white rounded-xl shadow-lg border border-gray-200 py-1 z-50">
                      <div className="px-3 py-2.5 border-b border-gray-100">
                        <p className="text-sm font-semibold text-gray-900">{currentUser.name}</p>
                        <p className="text-xs text-gray-500 mt-0.5">{currentUser.email}</p>
                      </div>
                      {[
                        { label: "Profilul meu", icon: "user", page: "profile" },
                        { label: "Anunțurile mele", icon: "file-text", page: "profile" },
                        { label: "Favorite", icon: "heart", page: "favorites" },
                        { label: "Adaugă anunț", icon: "plus", page: "create" },
                      ].map(item => (
                        <button
                          key={item.label}
                          onClick={() => { navigate(item.page); setProfileOpen(false); }}
                          className="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                        >
                          <IconsSVG name={item.icon} size={14} className="text-gray-400" />
                          {item.label}
                        </button>
                      ))}
                      {currentUser.role === "admin" && (
                        <button
                          onClick={() => { navigate("admin"); setProfileOpen(false); }}
                          className="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-purple-600 hover:bg-purple-50 transition-colors"
                        >
                          <IconsSVG name="shield" size={14} className="text-purple-400" />
                          Admin Panel
                        </button>
                      )}
                      <div className="border-t border-gray-100 mt-1 pt-1">
                        <button
                          onClick={() => { onLogout(); setProfileOpen(false); }}
                          className="flex items-center gap-2.5 w-full px-3 py-2 text-sm text-red-500 hover:bg-red-50 transition-colors"
                        >
                          <IconsSVG name="log-out" size={14} className="text-red-400" />
                          Deconectare
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="flex items-center gap-2 ml-1">
                <button
                  onClick={() => navigate("auth")}
                  className="px-4 py-2 text-sm font-medium text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
                >
                  Autentificare
                </button>
                <button
                  onClick={() => navigate("auth")}
                  className="px-4 py-2 text-sm font-semibold text-white bg-green-600 rounded-lg hover:bg-green-700 transition-colors"
                >
                  Înregistrare
                </button>
              </div>
            )}
          </div>

          {/* ── Mobile hamburger ── */}
          <button
            onClick={() => setMobileOpen(!mobileOpen)}
            className="md:hidden p-2 rounded-lg text-gray-600 hover:bg-gray-100 transition-colors"
          >
            <IconsSVG name={mobileOpen ? "x" : "menu"} size={20} />
          </button>
        </div>

        {/* ── Mobile menu ── */}
        {mobileOpen && (
          <div className="md:hidden border-t border-gray-100 py-3 space-y-1">
            {/* Mobile search */}
            <div className="pb-2">
              <div className="relative">
                <div className="absolute inset-y-0 left-3 flex items-center pointer-events-none">
                  <IconsSVG name="search" size={15} className="text-gray-400" />
                </div>
                <input
                  type="text"
                  placeholder="Caută anunțuri..."
                  className="w-full pl-9 pr-4 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-green-500"
                />
              </div>
            </div>

            {navLinks.map(link => (
              <button
                key={link.page}
                onClick={() => { navigate(link.page); closeAll(); }}
                className={`block w-full text-left px-3 py-2.5 text-sm font-medium rounded-lg ${
                  currentPage === link.page ? "text-green-600 bg-green-50" : "text-gray-700 hover:bg-gray-50"
                }`}
              >
                {link.label}
              </button>
            ))}

            {currentUser ? (
              <>
                <button onClick={() => { navigate("profile"); closeAll(); }} className="block w-full text-left px-3 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 rounded-lg">
                  Profilul meu
                </button>
                <button onClick={() => { navigate("create"); closeAll(); }} className="w-full flex items-center justify-center gap-1.5 bg-green-600 text-white text-sm font-semibold rounded-lg px-3 py-2.5 mt-1">
                  <IconsSVG name="plus" size={14} />
                  Adaugă anunț
                </button>
                <button onClick={() => { onLogout(); closeAll(); }} className="block w-full text-left px-3 py-2.5 text-sm font-medium text-red-500 hover:bg-red-50 rounded-lg">
                  Deconectare
                </button>
              </>
            ) : (
              <div className="flex gap-2 pt-1">
                <button onClick={() => { navigate("auth"); closeAll(); }} className="flex-1 py-2.5 text-sm font-medium text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50">
                  Autentificare
                </button>
                <button onClick={() => { navigate("auth"); closeAll(); }} className="flex-1 py-2.5 text-sm font-semibold text-white bg-green-600 rounded-lg hover:bg-green-700">
                  Înregistrare
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </nav>
  );
}

window.Navbar = Navbar;
